prior:
  gyroscope_bias: [-0.546656, -6.59877e-05, 0.00244956]
  accelerometer_bias: [0.0737028, -0.0178264, -0.000426039]
  
  
  
  # base_orientation: [1,0,0,0]
  # base_velocity: [0,0,0]
  # base_position: [0,0,0]
  # base_orientation_std: 0.1
  # base_velocity_std: 0.1
  # base_position_std: 0.001
  # gyroscope_bias_std: 0.0001
  # accelerometer_bias_std: 0.0001
