settings:
  initialize_state_from_first_observation: false
  imu_topic: "/lcm_publisher_node/imu"
  map_frame_id : "/odom"
  base_frame_id: "/husky/imu"
  pose_topic: "/husky/inekf_estimation/pose"
  state_topic: "/husky/inekf_state"
  visualization_markers_topic: "/husky/markers"
  enable_kinematics: true
  flat_ground: false
  kinematics_topic: "/lcm_publisher_node/kinematics"
  contact_topic: "/lcm_publisher_node/contact"
  
  # LCM handler
  # lcm_enable_debug_output: false
  # project_root_dir: "/home/arthuzh/CURLY/catkin_ws/src/cheetah_inekf_lcm"
  
  # Body Estimator
  estimator_publish_visualization_markers: true
  estimator_enable_debug: false
  estimator_static_bias_initialization: false

  # Cheetah System
  system_enable_pose_publisher: true
  system_inekf_pose_filename: "/media/jetson256g/data/inekf_result/husky_inekf_pose_kitti.txt"
  system_inekf_tum_pose_filename: "/media/jetson256g/data/inekf_result/husky_inekf_pose_tum.txt"