settings:
  initialize_state_from_first_observation: false
  imu_topic: "/gx5_0/imu/data"
  joint_topic: "/joint_states"
  map_frame_id : "/odom"
  base_frame_id: "/husky/imu"
  pose_topic: "/husky/inekf_estimation/pose"
  state_topic: "/husky/inekf_state"
  visualization_markers_topic: "/husky/markers"
  enable_kinematics: true
  flat_ground: false

  velocity_type: 3  # 1 for joint_state, 2 for gps_vel, 3 for camera_odom
  velocity_topic: "/zed_node/odom" # "/joint_states", "/gps/vel", "/zed_node/odom"

  # Body Estimator
  estimator_publish_visualization_markers: true
  estimator_enable_debug: false
  estimator_static_bias_initialization: true
  estimator_velocity_time_threshold: 0.5

  # Husky System
  system_enable_pose_publisher: true
  system_enable_pose_logger: true
  system_log_pose_skip: 10
  system_inekf_pose_filename: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/husky_inekf_pose_kitti.txt"
  system_inekf_tum_pose_filename: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/husky_inekf_camera_odom_test.txt"
  system_velocity_type: 1

  # Path Publisher
  pose_topic: "/husky/inekf_estimation/pose"
  path_topic: "/husky/inekf_estimation/path"
  publish_rate: 1000
  pose_skip: 10