settings:
  initialize_state_from_first_observation: false
  imu_topic: "/gx5_1/imu/data" # "/gx5_0/imu/data", "/carla/ego_vehicle/imu", "imu_with_noise", "/imu/data"
  joint_topic: "/joint_states"
  map_frame_id : "/odom"
  base_frame_id: "/husky/imu" 
  pose_topic: "/husky/inekf_estimation/pose"
  state_topic: "/husky/inekf_state"
  visualization_markers_topic: "/husky/markers"
  enable_kinematics: true
  flat_ground: false

  # "/joint_states", "/gps/vel", "/zed_node/odom", "/carla/ego_vehicle/odometry", "carla_velocity"
  enable_wheel_velocity_update: true
  wheel_velocity_topic: "/joint_states"
  enable_camera_velocity_update: true
  camera_velocity_topic: "/zed_node/odom"
  enable_gps_velocity_update: false
  gps_velocity_topic: "/gps/vel"

  # Body Estimator
  estimator_publish_visualization_markers: true
  estimator_enable_debug: false
  estimator_static_bias_initialization: true
  estimator_init_bias_using_orientation_est_from_imu: true
  estimator_velocity_time_threshold: 0.5

  # Husky System
  system_enable_pose_publisher: true
  system_enable_pose_logger: true
  system_enable_debug_logger: true
  system_log_pose_skip: 0
  system_inekf_pose_filename: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_husky_inekf_pose_kitti.txt"
  system_inekf_tum_pose_filename: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_husky_inekf_pose_tum.txt"
  system_inekf_vel_est_file_name: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_vel_est.txt"
  system_inekf_bias_est_file_name: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_bias_est.txt"
  system_inekf_vel_input_file_name: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_vel_input.txt"
  system_inekf_imu_file_name: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_imu.txt"
  system_velocity_type: 1

  # Path Publisher
  pose_topic: "/husky/inekf_estimation/pose"
  path_topic: "/husky/inekf_estimation/path"
  publish_rate: 1000
  pose_skip: 1
  
  
  rotation_body_imu: [0, 0.7071, -0.7071, 0] # Quaternion [w,x,y,z]

  # odom_to_imu
  # Husky:
  # translation:  [-66.465, 28.652, 0.132]
  # roataion: [0.000, 0.000, -0.471, 0.882] # Quaternion
  # Carla:
  # translation: [0, 0, 0]
  # rotation: [0, 0, 0, 1]