settings:

  imu_topic: "/gx5_0/imu/data" 
  joint_topic: "/joint_states"
  
  ###############################################################################
  # Velocity update flags. We use body velocity to correct the filter. 
  # We provide 3 different message types for body velocity input:
  # sensor_msgs::JointState, nav_msgs::Odometry, and geometry_msgs::TwistStamped
  ###############################################################################

  # Enable correction using body velocity estimated from wheel encoders
  # Input message type: sensor_msgs::JointState
  # We use v_wheel = angluar_velocity * wheel_radius. v_body = (v_right_wheel + v_left_wheel)/2.
  enable_wheel_velocity_update: true
  wheel_velocity_topic: "/joint_states"
  wheel_radius: 0.1651    # wheel radius (m). 
  vehicle_track_width: 0.555  # distance between right and left wheel (m).

  # Enable correction using body velocity estimated from camera odometry
  # Input message type: nav_msgs::Odometry
  # Note: The input source does not necessary need to be coming from camera odometry.
  # This correction works for any body velocity input published in nav_msgs::Odometry
  enable_camera_velocity_update: false
  camera_velocity_topic: "/zed_node/odom"

  # Enable correction using body velocity estimated from GPS
  # Input message type: geometry_msgs::TwistStamped
  # Note: The input source does not necessary need to be coming from GPS.
  # This correction works for any body velocity input published in geometry_msgs::TwistStamped
  
  enable_gps_velocity_update: false
  gps_velocity_topic: "/gps/vel"


  # Body Estimator
  estimator_enable_debug: false
  estimator_static_bias_initialization: true
  estimator_init_bias_using_orientation_est_from_imu: true
  estimator_velocity_time_threshold: 0.5

  # Husky System
  system_enable_pose_publisher: true
  system_enable_pose_logger: true
  system_enable_debug_logger: true
  system_log_pose_skip: 0
  system_inekf_pose_filename: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_husky_inekf_pose_kitti.txt"
  system_inekf_tum_pose_filename: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_husky_inekf_pose_tum.txt"
  system_inekf_vel_est_file_name: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_vel_est.txt"
  system_inekf_bias_est_file_name: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_bias_est.txt"
  system_inekf_vel_input_file_name: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_vel_input.txt"
  system_inekf_imu_file_name: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/04_cam_imu.txt"


  # publisher
  map_frame_id : "/odom"
  base_frame_id: "/husky/imu" 
  pose_topic: "/husky/inekf_estimation/pose"
  path_topic: "/husky/inekf_estimation/path"
  publish_rate: 1000
  pose_skip: 1
  


  rotation_body_imu: [0, 0.7071, -0.7071, 0] # Quaternion [w,x,y,z]
  rotation_cam_imu: [1,0,0,0]
  translation_cam_imu: [0,0,0]

  # odom_to_imu
  # Husky:
  # translation:  [-66.465, 28.652, 0.132]
  # roataion: [0.000, 0.000, -0.471, 0.882] # Quaternion
  # Carla:
  # translation: [0, 0, 0]
  # rotation: [0, 0, 0, 1]