settings:
  initialize_state_from_first_observation: false
  imu_topic: "/gx5_0/imu/data"
  map_frame_id : "/odom"
  base_frame_id: "/husky/imu"
  pose_topic: "/husky/inekf_estimation/pose"
  state_topic: "/husky/inekf_state"
  visualization_markers_topic: "/husky/markers"
  enable_kinematics: true
  flat_ground: false

  
  # LCM handler
  # lcm_enable_debug_output: false
  # project_root_dir: "/home/arthuzh/CURLY/catkin_ws/src/cheetah_inekf_lcm"
  
  # Body Estimator
  estimator_publish_visualization_markers: true
  estimator_enable_debug: false
  estimator_static_bias_initialization: true

  # Husky System
  system_enable_pose_publisher: true
  system_log_pose_as_txt: true
  system_inekf_pose_filename: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/husky_inekf_pose_kitti.txt"
  system_inekf_tum_pose_filename: "/home/justin/code/husky_inekf_ws/catkin_ws/src/husky_inekf/data/husky_inekf_pose_tum.txt"

  # Path Publisher
  pose_topic: "/husky/inekf_estimation/pose"
  path_topic: "/husky/inekf_estimation/path"
  publish_rate: 1
  pose_skip: 1